### ISSUE TITLE
Null argument in function with @Retry causes NullPointerException 

### ISSUE THREAD

**Issue by j-sikora** [vladmihalcea/db-util#10]
How to generate an exception:
1. create method:
`@Retry(on = OptimisticLockException.class, times = 3)`
`public void testRetry(String x, String y)`

2. execute: `testRetry("TEST", null)`

Exception:

`java.lang.NullPointerException
        at com.vladmihalcea.util.ReflectionUtils.getAnnotation(ReflectionUtils.java:44)
        at com.vladmihalcea.concurrent.aop.OptimisticConcurrencyControlAspect.retry(OptimisticConcurrencyControlAspec
t.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        ...
`

I think fix can be apply by changing:
`Class[] argClasses = new Class[pjp.getArgs().length];`
`        for (int i = 0; i < pjp.getArgs().length; i++) {`
`           argClasses[i] = pjp.getArgs()[i].getClass();`
`        }`
`        method = pjp.getTarget().getClass().getMethod(pjp.getSignature().getName(), argClasses);`

to:
`
method = pjp.getTarget().getClass().getMethod(pjp.getSignature().getName(), signature.getParameterTypes());
`

**Comment by vladmihalcea** [comment]
Check out the [`OptimisticConcurrencyControlAspectTest`](https://github.com/vladmihalcea/db-util/blob/master/src/test/java/com/vladmihalcea/concurrent/aop/OptimisticConcurrencyControlAspectTest.java). Last time I run it, it was working just fine.

**Comment by j-sikora** [comment]
OptimisticConcurrencyControlAspectTest does not have such test case as I have reported.

**Comment by vladmihalcea** [comment]
Send me a Pull Request and I'll investigate it. Make sure you add a test case that proves your use case as well.

**Comment by j-sikora** [comment]
Ok. Could you give me permissions to write to repository (I have 403 error when I'm trying to push my commit)?

**Comment by vladmihalcea** [comment]
You don't need permissions if you fork the repository. That's how GitHub is supposed to work.

You fork the repo, do the change and send the PR.

**Comment by j-sikora** [comment]
Ok. Pull request was sent.

**Comment by vladmihalcea** [comment]
Thanks. I will review it when I have some time.

**Comment by vladmihalcea** [comment]
I integrated your PR and released version `1.0.2`. Thanks.
