### ISSUE TITLE
Create a JUnit 5 extension to for clearer tests

### ISSUE THREAD

**Issue by dpash** [vladmihalcea/db-util#15]
Currently, we need to write tests like:

    @Test 
    public void test() {
        SQLStatementCountValidator.reset();
        warehouseProductInfoService.findAllWithNPlusOne();
        assertSelectCount(1);
    }

It would be useful if we could write

    @ExtendWith(QueryCountExtension.class)
    public class Tests {

        @QueryCount(select = 1)
        public void test() {
            warehouseProductInfoService.findAllWithNPlusOne();
        }
    }

I can have a look at creating a pull request, but I wanted to get your feedback on whether this is something you'd be interested in and how you'd like the `@QueryCount` annotation to look like. I was thinking of having something like (with defaults): `@QueryCount(select = 0, insert = 0, update = 0, delete = 0, total = <sum of others>)`

I'd also suggest a number of methods that take a lambda:

    assertSelectCount(1, () -> warehouseProductInfoService.findAllWithNPlusOne());

so that you can do multiple assertions in the same test.

**Comment by vladmihalcea** [comment]
Looks like a good idea. Send me a Pull Request with a proposal for this.

**Comment by jeanbisutti** [comment]
[QuickPerf](https://github.com/quick-perf/quickperf) allows to do this. The QuickPerfTest JUnit 5 extension is published on snapshot artifact today but I plan to publish a non snapshot artifact probably just after this week. For JUnit 4 you have also a QuickPerfJUnitRunner and a QuickPerfSpringRunner. Hope it can help.

**Comment by vladmihalcea** [comment]
The project will be archived soon.
