### ISSUE TITLE
Logback vulnerabilities in 1.0.6 release

### ISSUE THREAD

**Issue by boroda4436** [vladmihalcea/db-util#19]
Hi! Do you have plans to publish version 1.0.7 on maven? For now, the latest version has logback vulnerabilities
<img width="662" alt="image" src="https://user-images.githubusercontent.com/13794896/181464049-09ba765d-2e6b-4f0a-9637-cc9392a5dcf1.png">

**Comment by vladmihalcea** [comment]
All the dependencies use `<scope>provided</scope>,` so they are not transitive.

Therefore, the library doesn't force you to use a dependency that has vulnerabilities as you have to declare all the dependencies explicitly in your project with higher version numbers.

I could do a release, but it will not change anything actually. The Logback version that your application is using is not the one from the `db-util`, but the one you declared explicitly in your `pom.xml` file.

**Comment by boroda4436** [comment]
Great, thanks!

**Comment by vladmihalcea** [comment]
Fixed. I revised the dependencies and changed the scope of the `logback` one for `test` only. There is a single transitive dependency now.
