### ISSUE TITLE
SQLStatementCountMismatchException is interpreted as a test error instead of a test failure by some test runners

### ISSUE THREAD

**Issue by cac03** [vladmihalcea/db-util#4]
Hi,

the ```SQLStatementCountMismatchException``` is interpreted as a test error instead of a test failure by some test runners.

With following sample test class:
``` java

import com.vladmihalcea.sql.SQLStatementCountValidator;
import org.junit.Test;

import static org.junit.Assert.*;

public class SampleTest {

  @Test
  public void testThatAlwaysFails() {
    assertTrue(false);
  }

  @Test
  public void testWithError() {
    throw new RuntimeException();
  }

  @Test
  public void sqlCountTest() {
    SQLStatementCountValidator.assertSelectCount(10);
  }
}
```
IDEA displays ```sqlCountTest()``` test as having an error from the tested source code instead of a test failure (e.g. ```testThatAlwaysFails()```) 
![nov15_221127](https://user-images.githubusercontent.com/13610290/32855265-3b0ea330-ca52-11e7-8738-56f8605119d6.png)

This is also applied when running tests with Maven:
``` 
$ mvn test
```
```
...
Results :

Failed tests:   testThatAlwaysFails(SampleTest)

Tests in error: 
  sqlCountTest(SampleTest): Expected 10 statements but recorded 0 instead!
  testWithError(SampleTest)

Tests run: 3, Failures: 1, Errors: 2, Skipped: 0
```

This happens because [SQLStatementCountMismatchException](https://github.com/vladmihalcea/db-util/blob/master/src/main/java/com/vladmihalcea/sql/exception/SQLStatementCountMismatchException.java) extends ``` RuntimeException ``` instead of ``` AssertionError ```.

If the ```SQLStatementCountMismatchException``` will extend the ```AssertionError``` I think it should be renamed to ```SQLStatementCountMismatchAssertionError``` and its subclasses also should contain ```AssertionError``` instead of ```Exception``` in their names.

I'd like to submit a PR if you don't mind the proposed changes

**Comment by vladmihalcea** [comment]
Sounds like a good idea, indeed. Send me a PR please.

**Comment by cac03** [comment]
[Done](https://github.com/vladmihalcea/db-util/pull/5)
