### ISSUE TITLE
Release a new version within latest datasource-proxy migration

### ISSUE THREAD

**Issue by Tradunsky** [vladmihalcea/db-util#6]
The last update of db-util on maven central was 28-Jan-2014:
https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22db-util%22

That is pretty old one. Today I've faced that I need both db-util in test scope and datasource-proxy in compile. The issue is that db-utils was failing on 1.4.7 datasource-proxy..

I made a temporary workaround for the datasource-proxy which db-util is using, but I would like to get both datasource-proxy 1.4.7 and db-util without any additional effort to make them live with each other. 

Thanks

**Comment by vladmihalcea** [comment]
Send me a Pull Request with the changes and copy the Maven release from FlexyPool as well. I'll review it when it's done.

**Comment by Tradunsky** [comment]
As I understood, you are planning to migrate from https://github.com/ttddyy/datasource-proxy to https://github.com/vladmihalcea/flexy-pool
Not sure if it is exactly what I'm looking for. However, I will dig into flexy-pool later

**Comment by vladmihalcea** [comment]
Fixed. I released version 1.0.1 on Maven Central. Thanks.

**Comment by Tradunsky** [comment]
Thank you!
